name: Create Cluster

on: [push, pull_request]


jobs:

  create-cluster:
    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: install k3d
        run: |
          mkdir -p $HOME/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          curl -L https://github.com/rancher/k3d/releases/download/v4.5.0-dev.1/k3d-linux-amd64 --output k3d-linux-amd64
          mv k3d-linux-amd64 $HOME/.local/bin/k3d
          chmod +x $HOME/.local/bin/k3d

      - name: k3d
        run: k3d --version

      - name: run cluster
        run: k3d cluster create --servers=3 --subnet=auto

      - name: restart docker
        run: sudo systemctl stop docker && sudo systemctl start docker

      - name: docker ps
        run: docker ps
